version: '3.8'
services:
  
  web:
    container_name: "web_name"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    # working_dir: /app
    # command: npm run dev
    # environment:
    #   - NODE_ENV=development
    depends_on:
      - api
  nginxser:
    container_name: nginx_name
    image: nginx
    ports:
      - "80:80"
    # depends_on:
    #   - web
  api:
    container_name: "api_name"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/app
    # working_dir: /app
    # command: npm run dev
    # environment:
    #   - NODE_ENV=development
    # depends_on:
    #   - db